apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - https://docs.projectcalico.org/v3.20/manifests/calico.yaml
images:
- name: docker.io/calico/kube-controllers
  newName: quay.io/calico/kube-controllers
- name: docker.io/calico/node
  newName: quay.io/calico/node
- name: docker.io/calico/cni
  newName: quay.io/calico/cni
- name: docker.io/calico/pod2daemon-flexvol
  newName: quay.io/calico/pod2daemon-flexvol
